blank_issues_enabled: false

contact_links:
  - name: Hardware problem
    url: https://support.stereolabs.com/hc/en-us
    about: Go to Stereolabs support center and search for a known solution or write a direct email to support@stereolabs.com
  - name: Generic question about ZED cameras and their plugins
    url: https://community.stereolabs.com/
    about: Ask a question on the Stereolabs forum

