blank_issues_enabled: false

contact_links:
  - name: Generic question about ZED cameras and their plugins
    url: https://community.stereolabs.com/
    about: Ask a question on the Stereolabs forum
  - name: Report an Hardware problem
    url: mailto:support@stereolabs.com
    about: Write a direct email to the Stereolabs' support team
